const tips = [
  { text: "Start your day with the most important task first.", author: "Unknown", category: "Productivity" },
  { text: "Write down your goals to make them more concrete.", author: "Brian Tracy", category: "Goals" },
  { text: "Use a habit tracker to build consistency.", author: "James Clear", category: "Habits" },
  { text: "Break big goals into smaller milestones.", author: "Unknown", category: "Goals" },
  { text: "Start with just 2 minutes to beat procrastination.", author: "Leo Babauta", category: "Focus" },
  { text: "Pair new habits with existing routines.", author: "James Clear", category: "Habits" },
  { text: "Review your progress weekly to stay on track.", author: "Unknown", category: "Goals" },
  { text: "Create a morning routine that energizes you.", author: "Hal Elrod", category: "Mindset" },
  { text: "Celebrate small wins to stay motivated.", author: "Unknown", category: "Motivation" },
  { text: "Avoid multitasking — focus on one thing at a time.", author: "Cal Newport", category: "Focus" },
  { text: "Keep your goals visible — use sticky notes or screensavers.", author: "Unknown", category: "Goals" },
  { text: "Drink water first thing in the morning.", author: "Unknown", category: "Health" },
  { text: "Go to bed and wake up at consistent times.", author: "Matthew Walker", category: "Health" },
  { text: "Use visual cues to remind yourself of habits.", author: "James Clear", category: "Habits" },
  { text: "Limit screen time before bed for better sleep.", author: "Unknown", category: "Health" },
  { text: "Practice gratitude daily — write 3 things you’re thankful for.", author: "Unknown", category: "Mindset" },
  { text: "Set deadlines for personal goals.", author: "Napoleon Hill", category: "Goals" },
  { text: "Say no to tasks that don’t serve your priorities.", author: "Greg McKeown", category: "Focus" },
  { text: "Use the 80/20 rule: Focus on what brings the most results.", author: "Pareto Principle", category: "Productivity" },
  { text: "Track your habits to increase awareness.", author: "James Clear", category: "Habits" },
  { text: "Read at least 10 pages of a book daily.", author: "Unknown", category: "Learning" },
  { text: "Plan your day the night before.", author: "Brian Tracy", category: "Productivity" },
  { text: "Practice deep breathing when stressed.", author: "Unknown", category: "Health" },
  { text: "Delete distractions from your phone's home screen.", author: "Unknown", category: "Focus" },
  { text: "Keep a journal to reflect on your progress.", author: "Unknown", category: "Mindset" },
  { text: "Limit social media to fixed times per day.", author: "Cal Newport", category: "Focus" },
  { text: "Set a weekly goal and review it every Sunday.", author: "Unknown", category: "Goals" },
  { text: "Make habits enjoyable by rewarding yourself.", author: "James Clear", category: "Habits" },
  { text: "Use a calendar to block time for your priorities.", author: "Unknown", category: "Productivity" },
  { text: "Stay accountable by sharing your goals with a friend.", author: "Unknown", category: "Accountability" },
];
module.exports = tips;